name: MMCEssentials
main: net.moddedminecraft.mmcessentials.MMCEssentials
version: 0.9.5
author: Lee_lawd93
depend: [ProtocolLib]
commands:
  setprefix:
    description: Set a prefix.
    usage: /setprefix [prefix]
  delprefix:
    description: Delete a prefix.
    usage: /delprefix
  blockinfo:
    description: get the block information.
    usage: /Blockfinfo
  mmce:
    description: Main command for MMC Essentials.
    usage: /MMCE help
  whois:
    description: Determine the username behind a nickname
    usage: /whois [nickname]
  reboot:
    description: restart the server!
    usage: /Reboot help
  gm:
    description: Change your gamemode.
    usage: /gm
permissions:
  mmcessentials.*:
    description: Provide all the permissions.
    children:
      mmcessentials.reload: true
      mmcessentials.reboot.now: true
      mmcessentials.reboot.autorestart: true
      mmcessentials.reboot.vote: true
      mmcessentials.reboot.vote.bypass: true
      mmcessentials.reboot.cancel: true
      mmcessentials.reboot.debug: true
      mmcessentials.reboot.schedule: true
      mmcessentials.hideplugins.bypass: true
    default: op
  mmcessentials.reload:
    description: Reload of the config.yml.
    default: op
  mmcessentials.reboot.now:
    description: reboot the server immediatly.
    default: op
  mmcessentials.reboot.autorestart:
    description: Enable or Disable the auto restart function.
    default: op
  mmcessentials.reboot.vote:
    description: Start a vote for a restart.
    default: op
  mmcessentials.reboot.vote.bypass:
    description: Bypass the vote restrictions (players online, time limits)
    default: op
  mmcessentials.reboot.limit:
    description: Limit the time scheduled restart to between 1-5 minutes
    default: false
  mmcessentials.reboot.cancel:
    description: Cancel any exsisting restart / vote
    default: op
  mmcessentials.reboot.debug:
    description: Debug commands
    default: op
  mmcessentials.reboot.schedule:
    description: Schedule a restart after a given time.
    default: op
  mmcessentials.hideplugins.bypass:
    description: Bypass the hide plugin's function to show the real information.
    default: op
  mmcessentials.prefix.set:
    description: Set your own prefix.
    default: op
  mmcessentials.prefix.del:
    description: Delete your own prefix.
    default: op
  mmcessentials.prefix.del.others:
    description: Delete another players prefix.
    default: op
  mmcessentials.prefix.set.others:
    description: Set another players prefix.
    default: op
  mmcessentials.command.gamemode:
    description: Change your gamemode.
    defailt: op
  mmcessentials.prefix.protect:
    description: Protect your prefix from being changed..
    defailt: op